// ── DisclaimerBanner — Person 4 (Phase 3, Task 3) ───────────────────────────
// Fully styled persistent disclaimer component.
// Color shifts based on verdict: amber for confirmed/unverified, rose/red for contradicted.
// Always includes the API safety_disclaimer, a hardcoded system explanation,
// and an emergency resources row.

import type { Verdict } from "./StatusPanel";

interface DisclaimerBannerProps {
  message: string;
  verdict: Verdict;
}

// ── Style maps per verdict ────────────────────────────────────────────────────

const WRAPPER_STYLE: Record<Verdict, string> = {
  confirmed:
    "border-amber-400/50 bg-amber-400/10 shadow-[0_0_24px_-6px_rgba(251,191,36,0.2)]",
  unverified:
    "border-amber-400/40 bg-amber-400/8 shadow-[0_0_24px_-6px_rgba(251,191,36,0.15)]",
  contradicted:
    "border-rose-500/50 bg-rose-500/10 shadow-[0_0_24px_-6px_rgba(239,68,68,0.2)]",
};

const LABEL_STYLE: Record<Verdict, string> = {
  confirmed: "text-amber-400",
  unverified: "text-amber-400",
  contradicted: "text-rose-400",
};

const MESSAGE_STYLE: Record<Verdict, string> = {
  confirmed: "text-amber-200",
  unverified: "text-amber-200/90",
  contradicted: "text-rose-200",
};

const DIVIDER_STYLE: Record<Verdict, string> = {
  confirmed: "border-amber-400/20",
  unverified: "border-amber-400/15",
  contradicted: "border-rose-500/20",
};

const SYSTEM_LINE_STYLE: Record<Verdict, string> = {
  confirmed: "text-amber-300/70",
  unverified: "text-amber-300/60",
  contradicted: "text-rose-300/70",
};

const LINK_STYLE: Record<Verdict, string> = {
  confirmed: "text-amber-300 hover:text-amber-100 ring-amber-400/30 hover:ring-amber-400/60",
  unverified: "text-amber-300 hover:text-amber-100 ring-amber-400/30 hover:ring-amber-400/60",
  contradicted: "text-rose-300 hover:text-rose-100 ring-rose-500/30 hover:ring-rose-500/60",
};

const VERDICT_ICON: Record<Verdict, string> = {
  confirmed: "⚠️",
  unverified: "⚠️",
  contradicted: "🚨",
};

// ── Emergency resource links ──────────────────────────────────────────────────

const EMERGENCY_LINKS = [
  {
    label: "NWS Fort Worth",
    href: "https://www.weather.gov/fwd/",
    icon: "🌩️",
  },
  {
    label: "Call 911",
    href: "tel:911",
    icon: "🚨",
  },
  {
    label: "ERCOT Outage Map",
    href: "https://www.ercot.com/gridinfo/resource",
    icon: "⚡",
  },
];

// ── Component ─────────────────────────────────────────────────────────────────

export default function DisclaimerBanner({ message, verdict }: DisclaimerBannerProps) {
  return (
    <div
      role="alert"
      aria-live="polite"
      className={`rounded-xl border backdrop-blur-sm px-5 py-4 space-y-3 transition-all duration-300 ${WRAPPER_STYLE[verdict]}`}
    >
      {/* ── Header label ──────────────────────────────────────────────── */}
      <div className="flex items-center gap-2">
        <span aria-hidden="true" className="text-base">{VERDICT_ICON[verdict]}</span>
        <p className={`text-xs font-semibold uppercase tracking-widest ${LABEL_STYLE[verdict]}`}>
          Safety Notice
        </p>
      </div>

      {/* ── API safety disclaimer message ─────────────────────────────── */}
      <p className={`text-sm leading-relaxed ${MESSAGE_STYLE[verdict]}`}>
        {message}
      </p>

      {/* ── Hardcoded system explanation line ─────────────────────────── */}
      <p className={`text-xs leading-relaxed italic ${SYSTEM_LINE_STYLE[verdict]}`}>
        This analysis was generated by an AI system cross-referencing live NWS,
        ERCOT, and local PD feeds. It does not replace official emergency guidance.
      </p>

      {/* ── Divider ───────────────────────────────────────────────────── */}
      <hr className={`border-t ${DIVIDER_STYLE[verdict]}`} />

      {/* ── Emergency resources row ───────────────────────────────────── */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <span className={`text-xs font-semibold uppercase tracking-wider ${LABEL_STYLE[verdict]}`}>
          Emergency Resources:
        </span>
        {EMERGENCY_LINKS.map((link) => (
          <a
            key={link.label}
            href={link.href}
            target={link.href.startsWith("tel:") ? "_self" : "_blank"}
            rel="noopener noreferrer"
            className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium ring-1 transition-all duration-200 ${LINK_STYLE[verdict]}`}
          >
            <span aria-hidden="true">{link.icon}</span>
            {link.label}
          </a>
        ))}
      </div>
    </div>
  );
}
