import type { Verdict } from "./StatusPanel";

interface DisclaimerBannerProps {
  message: string;
  verdict: Verdict;
}

const BORDER: Record<Verdict, string> = {
  confirmed: "border-amber-400/20",
  unverified: "border-amber-400/15",
  contradicted: "border-rose-500/20",
};

const LABEL: Record<Verdict, string> = {
  confirmed: "text-amber-400",
  unverified: "text-amber-400",
  contradicted: "text-rose-400",
};

const BODY: Record<Verdict, string> = {
  confirmed: "text-amber-200/80",
  unverified: "text-amber-200/70",
  contradicted: "text-rose-200/80",
};

const EMERGENCY_LINKS = [
  { label: "NWS Fort Worth", href: "https://www.weather.gov/fwd/" },
  { label: "Call 911", href: "tel:911" },
  { label: "ERCOT Outage Map", href: "https://www.ercot.com/gridinfo/resource" },
];

export default function DisclaimerBanner({ message, verdict }: DisclaimerBannerProps) {
  return (
    <div
      role="alert"
      aria-live="polite"
      className={`rounded-sm border px-4 py-4 space-y-3 ${BORDER[verdict]}`}
      style={{ background: "rgba(0,0,0,0.2)" }}
    >
      <p className={`text-xs font-semibold uppercase ${LABEL[verdict]}`} style={{ letterSpacing: "0.1em" }}>
        Safety Notice
      </p>

      <p className={`text-xs leading-relaxed font-light ${BODY[verdict]}`}>{message}</p>

      <p className="text-xs leading-relaxed italic text-slate-500 font-light">
        This analysis was generated by an AI system cross-referencing live NWS, ERCOT, and local PD
        feeds. It does not replace official emergency guidance.
      </p>

      <div className="pt-1 border-t border-white/[0.05]">
        <p className={`text-xs font-medium mb-2 ${LABEL[verdict]}`} style={{ letterSpacing: "0.06em" }}>
          Emergency Resources
        </p>
        <div className="flex flex-wrap gap-x-4 gap-y-1">
          {EMERGENCY_LINKS.map((link) => (
            <a
              key={link.label}
              href={link.href}
              target={link.href.startsWith("tel:") ? "_self" : "_blank"}
              rel="noopener noreferrer"
              className="text-xs text-slate-400 hover:text-slate-200 underline underline-offset-2 transition-colors font-light"
            >
              {link.label}
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
